### ISSUE TITLE
If both APP_NAME and name in manifest are "MozApps", install silently fails

### ISSUE THREAD

**Issue by nickdesaulniers** [digitarald/make-fxos-install#1]
https://github.com/digitarald/make-fxos-install/blob/master/Makefile#L5
->
APP_NAME = MozApps

and make app manifest name field:
MozApps

app installs, you get the window hanger, but no icon.  Unfortunate naming scheme

**Comment by digitarald** [comment]
Fixed with setting lowercase ID from folder in Makefile
